name = "halos-api"
main = "src/worker.js"
compatibility_date = "2024-03-01"

# Serves static frontend assets alongside Worker API routes
[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "my-d"
database_id = "96063eba-fdc4-4423-a790-d464d231b0f0" # Replace after running: npx wrangler d1 create halos-db